[[bin]]
name = 'zeitgeist'
path = './src/main.rs'

[build-dependencies]
substrate-build-script-utils = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }

[dependencies]
hex-literal = { version = "0.2" }
jsonrpc-core = { version = "15.0" }
pallet-transaction-payment-rpc = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sc-basic-authorship = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sc-cli = { branch = "moonbeam-polkadot-v0.9.10", features = ["wasmtime"], git = "https://github.com/purestake/substrate" }
sc-client-api = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sc-consensus = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sc-executor = { branch = "moonbeam-polkadot-v0.9.10", features = ["wasmtime"], git = "https://github.com/purestake/substrate" }
sc-keystore = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sc-rpc = { branch = "moonbeam-polkadot-v0.9.10",  git = "https://github.com/purestake/substrate" }
sc-rpc-api = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sc-service = { branch = "moonbeam-polkadot-v0.9.10", features = ["wasmtime"], git = "https://github.com/purestake/substrate" }
sc-telemetry = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sc-transaction-pool = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sc-transaction-pool-api = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sp-api = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sp-block-builder = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sp-blockchain = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sp-consensus = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sp-core = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sp-runtime = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sp-timestamp = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
structopt = { version = "0.3" }
substrate-frame-rpc-system = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }

# Benchmark

frame-benchmarking = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate", optional = true }
frame-benchmarking-cli = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate", optional = true }

# Cumulus

cumulus-client-cli = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/cumulus" }
cumulus-client-collator = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/cumulus" }
cumulus-client-consensus-relay-chain = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/cumulus" }
cumulus-client-network = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/cumulus" }
cumulus-client-service = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/cumulus" }
cumulus-primitives-core = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/cumulus" }
cumulus-primitives-parachain-inherent = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/cumulus" }

# Parachain

log = { version = "0.4" }
nimbus-consensus = { branch = "moonbeam-polkadot-v0.9.10", default-features = false, git = "https://github.com/purestake/cumulus" }
nimbus-primitives = { branch = "moonbeam-polkadot-v0.9.10", default-features = false, git = "https://github.com/purestake/cumulus" }
pallet-author-inherent = { branch = "moonbeam-polkadot-v0.9.10", default-features = false, git = "https://github.com/purestake/cumulus" }
parachain-staking = { branch = "master", git = "https://github.com/PureStake/moonbeam" }
parity-scale-codec = { version = "2.0" }
sc-chain-spec = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
sc-tracing = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }
serde = { features = ["derive"], version = "1.0" }
sp-trie = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/substrate" }

# Polkadot

polkadot-cli = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/polkadot" }
polkadot-parachain = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/polkadot" }
polkadot-primitives = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/polkadot" }
polkadot-service = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/polkadot" }
polkadot-test-service = { branch = "moonbeam-polkadot-v0.9.10", git = "https://github.com/purestake/polkadot" }

# Zeitgeist

zeitgeist-primitives = { path = "../primitives" }
zeitgeist-runtime = { path = "../runtime" }
zrml-liquidity-mining = { path = "../zrml/liquidity-mining" }
zrml-swaps-rpc = { path = "../zrml/swaps/rpc" }

[features]
default = []
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-benchmarking-cli",
    "polkadot-service/runtime-benchmarks",
    "zeitgeist-runtime/runtime-benchmarks"
]

[package]
authors = ['Zeitgeist PM <contact@zeitgeist.pm>']
build = 'build.rs'
description = 'An evolving blockchain for prediction markets and futarchy.'
edition = '2018'
homepage = 'https://zeitgeist.market'
name = 'zeitgeist-node'
version = '0.2.0'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
