name: Rust

on:
  push:
    branches: [ main, chachacha ]
  pull_request:
    branches: [ main, chachacha ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializes
      run: |
        rustup install nightly-2021-03-10
        rustup target add wasm32-unknown-unknown --toolchain nightly-2021-03-10
        rustup component add rustfmt --toolchain nightly-2021-03-10-x86_64-unknown-linux-gnu
    - name: Rustfmt
      run: |
        cargo fmt --all -- --check
    - name: Builds WASM
      run: |
        make build-wasm
    - name: Build
      run: |
        cargo build
    - name: Runs tests
      run: |
        cargo test
